name: smart_home
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_spinkit: ^5.2.0
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  iconly: ^1.0.1
  icons_plus: ^5.0.0
  pinput: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

